# Generated by Django 4.0 on 2021-12-27 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='is_favorite',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
