# Generated by Django 4.0 on 2021-12-28 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sim_manager', '0005_rename_user_simulation_ownership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simulation',
            name='is_favorite',
        ),
        migrations.RemoveField(
            model_name='simulation',
            name='user',
        ),
    ]
