# Generated by Django 4.0 on 2021-12-28 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sim_manager', '0007_simulation_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simulation',
            name='user',
        ),
    ]
