# Generated by Django 4.0 on 2021-12-28 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim_manager', '0010_remove_simulation_is_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='is_favorite',
            field=models.BooleanField(default=0),
        ),
    ]
