# Generated by Django 4.0 on 2021-12-28 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('sim_manager', '0011_simulation_is_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='user_shared',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='user_shared', to='auth.user'),
        ),
    ]
