# Generated by Django 4.0 on 2021-12-28 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim_manager', '0019_alter_simulation_user_shared'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='is_shared',
            field=models.BooleanField(default=0),
        ),
    ]
