# Generated by Django 4.0 on 2021-12-29 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('sim_manager', '0021_remove_simulation_user_shared_share'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='user_shared',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.user'),
        ),
    ]
