# Generated by Django 3.2.9 on 2022-01-04 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sim_manager', '0022_alter_share_user_shared'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simulation',
            name='is_shared',
        ),
    ]
